### ISSUE TITLE
Generating graphs for benchmark results

### ISSUE THREAD

**Issue by mloskot** [DigitalInBlue/Celero#101]
This is not a real issue report.

I just wanted to share little utility script which I developed to generate pretty graphs from Celero results using Bokeh: https://github.com/mloskot/pycelerograph

I thought it might be useful to others.

Kudos for Celero, it's a great benchmarking tool!

**Comment by DigitalInBlue** [comment]
I like it.  Can you post a picture of its output?  Since it's just a single .py file, could I merge it into the regular Celero project?

**Comment by mloskot** [comment]
I have just added `gh-pages` (https://mloskot.github.io/pycelerograph/example/) with viewable sample HTML report (https://mloskot.github.io/pycelerograph/example/report.html).

> could I merge it into the regular Celero project?

Yes, of course. I've just released it though (as part of playing with my https://github.com/mloskot/string_benchmark).

For general public the script likely needs some work, perhaps make it more configurable with command line parameters for some control of bokeh layout, etc.

**Comment by mloskot** [comment]
I've updated the generator and here is sample of the current reports

http://mloskot.github.io/string_benchmark/results/

**Comment by mloskot** [comment]
@DigitalInBlue Thanks for the [little credit about pycelerograph in your CppCon 2017 talk](https://www.youtube.com/watch?v=dO-j3qp7DWw&t=36m38s) :)

**Comment by mloskot** [comment]
FYI, I have upgraded the script for support Bokrh 1.20 or later. Grab it from `master` branch or https://github.com/mloskot/pycelerograph/releases/tag/v1.0
