### ISSUE TITLE
Conan package for Celero library

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [DigitalInBlue/Celero#110]
Hello,
Can you add Conan package for the library?

**Comment by DigitalInBlue** [comment]
Please provide documentation and justification.  Nothing formal, but something.

**Comment by ZaMaZaN4iK** [comment]
Ok :-)
What is [Conan](http://docs.conan.io/en/latest/)
Example with ready recipe: [click](https://github.com/bincrafters/conan-libcurl)

**Comment by Ignition** [comment]
@DigitalInBlue a conan package definition should be stored in a repo separate to this one. Can you make a new repo something like `conan-celero` with just a README in it? A while ago I made https://github.com/Ignition/conan-celero-demo I can update to be based on the #115 and #116 changes and see where we get.

**Comment by DigitalInBlue** [comment]
Sure.  It will be a few hours.  I’ll reply here when it’s up.

**Comment by DigitalInBlue** [comment]
The repository was created at https://github.com/DigitalInBlue/Celero-Conan.

**Comment by robowen5mac** [comment]
Sorry to comment on a closed issue, but was curious if any progress had been made to add this to one of the various conan remotes so it can be used. From my searching I could not find it on any of the standard remotes, but realise I might have missed something obvious here.

**Comment by DigitalInBlue** [comment]
I am not aware of it being added anywhere.  I use vcpkg personally and maintain that as a package manager for Celero.  I'm happy to help with Conan where I can, but it isn't something I use.

**Comment by p-podsiadly** [comment]
Hello,
I couldn't find a Conan package for Celero, so I've created and uploaded one myself (it's based on what @Ignition did). Git repo is [here](https://github.com/p-podsiadly/Celero-Conan), and conan repository is [here](https://bintray.com/ppodsiadly/conan/celero%3Appodsiadly).
@DigitalInBlue if you're interested, I could submit a PR to your repo. Also, it might make sense to create Celero's organization on Bintray (the service for hosting conan packages) and upload the package there - right now, it's connected to my account. For example, developers of Catch did this: [link](https://bintray.com/catchorg).

In any case, I hope someone will find my package useful :) Thanks for work on Celero!
