### ISSUE TITLE
Rename #define BENCHMARK

### ISSUE THREAD

**Issue by mloskot** [DigitalInBlue/Celero#114]
Would it be possible to rename `#define BENCHMARK` to something more unique?

The generic `BENCHMARK` clashes with benchmarking feature in Catch2, see https://github.com/catchorg/Catch2/issues/1186

**Comment by DigitalInBlue** [comment]
I'm not going to disagree, but it would break all existing benchmarks to make it more unique at this point.

**Comment by mloskot** [comment]
I understand.
