### ISSUE TITLE
Correct color for columns bar

### ISSUE THREAD

**Issue by zaba963** [DigitalInBlue/Celero#131]
Eliminating colored sidebars from columns. Make columns appear more sharply and readable.
Test in my [fork](https://github.com/zaba963/Celero)

before:
![image](https://user-images.githubusercontent.com/11948700/54481192-c8255d00-4831-11e9-9590-bbed09589b18.png)

after:
![image](https://user-images.githubusercontent.com/11948700/54481256-c8722800-4832-11e9-9960-73d2703214d9.png)

**Comment by DigitalInBlue** [comment]
This is nice.  Please do a pull request against the ```develop``` branch.
