### ISSUE TITLE
Truncation of group and experiment names in standard output

### ISSUE THREAD

**Issue by mlohry** [DigitalInBlue/Celero#158]
# Issue Template

## Feature Request

The Group and Experiment columns in the standard output uses a fixed 15 characters, with longer names being truncated. Can this be automatically scaled to the width of the widest entry for readability?

**Comment by DigitalInBlue** [comment]
The group name column is now automatically resizing.  (The Experiment Name column is not.)  This issue and the corresponding fix only applies to the console output.  Text file output was not impacted.
