### ISSUE TITLE
Add User-Defined String field to Result Table CSV

### ISSUE THREAD

**Issue by ryansynk** [DigitalInBlue/Celero#169]
I would like to associate a string with each benchmark and have that string be written to the output CSV along with the measurement data. However, the `UserDefinedMeasurementTemplate` requires a numeric value. Is there any way to do this currently in celero?

i.e. have the CSV look something like
`Group, Experiment, Problem Space, Samples, Iterations, ..., Filename`

**Comment by DigitalInBlue** [comment]
Good idea.  I can take a look!

**Comment by ryansynk** [comment]
Great, thank you

**Comment by DigitalInBlue** [comment]
Apologies for the delay.  Looking at the code, I think ```UserDefinedMeasurementTemplate``` is just a convenience class.  You can use any type you want if you inherit from ```UserDefinedMeasurement``` instead.  It has a few pure virtual functions you have to implement, but it would be trivial for ```std::string``` to implement.

```cpp
///
/// \brief Must be implemented by the user. Must return a specification which aggregations the user wants to be computed.
///
virtual UDMAggregationTable getAggregationInfo() const = 0;

///
/// \brief Must be implemented by the user. Must return the name of this user-defined measurement.
///
virtual std::string getName() const = 0;

///
/// \brief Combine the results of two user-defined measurements.
///
/// As TestFixture classes are created and destroyed, this provides a mechanism to preserve data.  Internally, this function is used so that
/// each unique set of (group, experiment, problem space) has its own combined set of user defined measurements.
///
virtual void merge(const UserDefinedMeasurement* const x) = 0;
```

For your use case, `getAggregationInfo()` would just return an empty `UDMAggregationTable`.  and `merge` would not have to do anything at all.  So you would just have to return a name.  Give that a try and let me know if you have success.
