### ISSUE TITLE
Celero/experiments/ExperimentCompressBools has a bad cast

### ISSUE THREAD

**Issue by mt-xiyinli** [DigitalInBlue/Celero#170]
## Bug Report

in case Celero/experiments/ExperimentCompressBools 
‘’‘
	void setUp(const celero::TestFixture::ExperimentValue& experimentValue) override
	{
		CompressBoolsFixture::setUp(experimentValue);

		auto ev = dynamic_cast<const MyExperimentValue&>(experimentValue);
		this->numBytes = ev.NumBytes;
		this->numFullBytes = ev.NumFullBytes;
		this->outputValues.reset(new uint8_t[this->numBytes]);
	}
’‘’
the dynamic_cast is a bad cast when running
## Feature Request
i want add my experimentValue such as int x,y,z but the problespace show x*y*z，i follow this example but failed when running

**Comment by DigitalInBlue** [comment]
Thanks for pointing this out.  I've got a fix for this that will be merged in the next version.
