### ISSUE TITLE
Print of an additional ','

### ISSUE THREAD

**Issue by danielsaad** [DigitalInBlue/Celero#22]
Hello!

I noticed Celero is printing an additional ',' comma while exporting data to a csv file.
This could be annoying when plotting data.

**Comment by bkloppenborg** [comment]
I think this was fixed in f3d09869cba606168abd152700f929f75b36b588 . @DigitalInBlue do you concur?

**Comment by DigitalInBlue** [comment]
I do.  The issue can be closed.  Thanks.
