### ISSUE TITLE
CMake fails

### ISSUE THREAD

**Issue by sgwoodjr** [DigitalInBlue/Celero#60]
Hi,
I get the following error on the latest *master* branch:

[sgwood@mstdev31 Celero (master)]cmake .
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- SYSTEM: Linux
CMAKE_CXX_COMPILER: /usr/bin/c++
CMake Error at experiments/CMakeLists.txt:6 (ADD_SUBDIRECTORY):
  The source directory

    /nis_home/sgwood/programs/Celero/experiments/CMakeFiles

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by DigitalInBlue** [comment]
You shouldn't have a CMakeFiles directory.  When configuring CMake, ensure that you have a different "where is the code" directory from the "where to build the binary" directory.  Hopefully that helps.

**Comment by sgwoodjr** [comment]
Yep, that did it. Thanks.
