### ISSUE TITLE
`develop` is behind `master`

### ISSUE THREAD

**Issue by peterazmanov** [DigitalInBlue/Celero#86]
I want to propose some changes via pull request and guidelines tell me to submit it to `develop` branch. But after commit 4dca14122cb08c1ceae54b9a70db3ad62e2b6149 `develop` is behind `master`. Something is out of date, either guidelines or `develop` branch.

**Comment by DigitalInBlue** [comment]
Sorry.  Forgot to update ```develop``` after my last ```master``` update.  Should be resolved now!
