### ISSUE TITLE
provide output of statistics in tables (csv and table output)

### ISSUE THREAD

**Issue by nevion** [DigitalInBlue/Celero#92]
Statistics are computed but go nowhere, if I'm reading things right.  This affects confidence in the benchmark - variance/skewness notably, as well as min/max.

These are pretty important to show for benchmarks, IMHO.   Maybe provide some option to opt-in given the width of terminal it would require.

**Comment by DigitalInBlue** [comment]
The command line option `--outputTable output.csv` will give you all of the statistics computed.
