### ISSUE TITLE
General Program Flow: onExperimentStart

### ISSUE THREAD

**Issue by MariusHerget** [DigitalInBlue/Celero#94]
As far as I understand the code, the function _onExperimentStart_ gets executed after starting the timer and not before each sample as it is illustrated in the general program flow (TextFixture.cpp:65).

So therefore is there another  _onExperimentStart_ method or is the flow example wrong?

**Comment by DigitalInBlue** [comment]
Reasonable question.  The code was correct and the documentation was wrong.  The `onExperiment* `virtual functions ARE included in the measurement.  The `setup` and `tearDown` functions are NOT included in the measurement.  You can optionally overload whichever fit your needs.  The documentation has been corrected.
