### ISSUE TITLE
Results.csv file columns incorrect result

### ISSUE THREAD

**Issue by danielsaad** [DigitalInBlue/Celero#96]
Hello there!
I did run Celero Benchmark and generated a output to a csv file.
This is what I obtained:

Group   Experiment  Problem Space   Samples Iterations  Baseline    us/Iteration    Iterations/sec  Min (us)    Mean (us)   Max (us)
erastosthenes   serial_erastosthenes    10  1   3   1   0.666667    1500000 2   2   2
erastosthenes   serial_erastosthenes    100 1   3   1   0.666667    1500000 2   2   2
erastosthenes   serial_erastosthenes    1000    1   3   1   2.66667 375000  8   8   8
erastosthenes   serial_erastosthenes    10000   1   3   1   45.6667 21897.8 137 137 137
erastosthenes   serial_erastosthenes    100000  1   3   1   847.667 1179.71 2543    2543    2543
erastosthenes   serial_erastosthenes    1000000 1   3   1   7159.67 139.671 21479   21479   21479
erastosthenes   serial_erastosthenes    10000000    1   3   1   152912  6.53971 458736  458736  458736
erastosthenes   serial_erastosthenes    100000000   1   3   1   1665480 0.600427    4996442 4996440 4996442
erastosthenes   serial_erastosthenes    1000000000  1   3   1   18366800    0.054446    55100430    55100400    55100430

In some cases Min(us) > Mean(us). Perhaps the columns are not labeled in a correct way.

**Comment by DigitalInBlue** [comment]
It looks to me like the columns are correctly labeled.  I do see that the += operator and the + operator on the Statistics object were not handling the min and max values.  That is corrected now.  I wouldn't rule out that the mean is not being computed properly.
