### ISSUE TITLE
Static library built in VS2015 doesn't work

### ISSUE THREAD

**Issue by everyonecancode** [DigitalInBlue/Celero#99]
Hi,
I tried to create static library only build with VS2015. I received the .lib file (around 14MB), but when I tried to complle your runnable example, I received LNK2019 errors (log file attached). However, the same example, compiled with dynamic libs (40KB celero.lib and ~1MB celero.dll) builds and runs without a problem. 

[build.txt](https://github.com/DigitalInBlue/Celero/files/724859/build.txt)

**Comment by DigitalInBlue** [comment]
Did you compile with the CMake variable `CELERO_COMPILE_DYNAMIC_LIBRARIES` set to `OFF`?  If you did, there should be a precompiler definition of `CELERO_STATIC` for all of your projects.  When that is set, Export.h is supposed to give blank definitions to `CELERO_EXPORT` and `CELERO_EXPORT_C`.  When this is true, you will not have `__declspec(dllimport)` used in your project, but this is exactly what I see in your log file.  Check to make sure `CELERO_STATIC` is defined in all of your projects.

**Comment by everyonecancode** [comment]
While adding `CELERO_STATIC` did fix `_declspec(dllimport)` errors, I've got a new one:

`celerod.lib(Utilities.obj) : error LNK2019: unresolved external symbol CallNtPowerInformation referenced in function "void __cdecl celero::DisableDynamicCPUScaling(void)" (?DisableDynamicCPUScaling@celero@@YAXXZ)`

Again, same code (from the example you provided), works with dll build.

**Comment by DigitalInBlue** [comment]
See: https://msdn.microsoft.com/en-us/library/windows/desktop/aa372675(v=vs.85).aspx

Looks like PowrProf.lib needs to be included.  (I haven't actually built with static libraries myself.)

**Comment by everyonecancode** [comment]
Yes, adding PowrProf.lib fixed this issue.

Will you fix the static build or just advise against using it? Either way, I think it would be a good idea to update the README file on project's page.

**Comment by DigitalInBlue** [comment]
Great.  I will update the CMakeList.txt and push the change.  Thanks for
the debugging help.

**Comment by everyonecancode** [comment]
No problem. Thank you for creating this great library :)

**Comment by ZaMaZaN4iK** [comment]
Can you close this issue?

**Comment by MichaelMauderer** [comment]
Has this actually been fixed? I just ran into this issue (Visual Studio 14 2015 Win64).

**Comment by DigitalInBlue** [comment]
Was the issue that "PowrProf.lib" was not linked or is your problem a new issue?

**Comment by MichaelMauderer** [comment]
Yeah exactly. I got it fixed for our build, but it seems that the current fix in the Celero CMake file doesn't work.

**Comment by MichaelMauderer** [comment]
I only fixed the issue locally by adding a `target_link_libraries(PROJECTNAME PowrProf.lib)` to our build. I am not sure why the one from the Celero CMakeLists.txt did not do the job though.
